// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PrimeClient is the client API for Prime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrimeClient interface {
	Validate(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error)
}

type primeClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeClient(cc grpc.ClientConnInterface) PrimeClient {
	return &primeClient{cc}
}

func (c *primeClient) Validate(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error) {
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, "/Prime/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimeServer is the server API for Prime service.
// All implementations must embed UnimplementedPrimeServer
// for forward compatibility
type PrimeServer interface {
	Validate(context.Context, *ValidationRequest) (*ValidationResponse, error)
	mustEmbedUnimplementedPrimeServer()
}

// UnimplementedPrimeServer must be embedded to have forward compatible implementations.
type UnimplementedPrimeServer struct {
}

func (UnimplementedPrimeServer) Validate(context.Context, *ValidationRequest) (*ValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedPrimeServer) mustEmbedUnimplementedPrimeServer() {}

// UnsafePrimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimeServer will
// result in compilation errors.
type UnsafePrimeServer interface {
	mustEmbedUnimplementedPrimeServer()
}

func RegisterPrimeServer(s grpc.ServiceRegistrar, srv PrimeServer) {
	s.RegisterService(&Prime_ServiceDesc, srv)
}

func _Prime_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimeServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Prime/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimeServer).Validate(ctx, req.(*ValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Prime_ServiceDesc is the grpc.ServiceDesc for Prime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Prime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Prime",
	HandlerType: (*PrimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _Prime_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/prime.proto",
}
