"server":
    "port": 9000
"database":
    "host": "postgres"
    "port": 5432
    "user": "postgres"
    "password": "postgres"
    "db_name": "postgres"
    "ssl_mode": "disable"
    "max_open_conns": 20
    "max_idle_conns": 5
    "conn_max_lifetime": 10
    "migrate_source": "file:///opt/prime/migrations"
